services:
  - type: worker
    name: betboom-bot
    env: docker
    plan: free
    image: python:3.13

    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libnss3 \
        libatk-bridge2.0-0 \
        libdrm2 \
        libxkbcommon0 \
        libgbm1 \
        libasound2 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgtk-3-0 \
        libxshmfence1 \
        libegl1 \
        wget \
        curl \
        xvfb
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      # Устанавливаем Playwright и браузеры прямо в системный каталог
      python -m playwright install-deps
      python -m playwright install chromium --with-deps
      mkdir -p /ms-playwright
      cp -r /root/.cache/ms-playwright/* /ms-playwright/ || true

    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      python railway_bot.py
