services:
  - type: worker
    name: betboom-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python railway_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9  # Используем Python 3.11 для лучшей совместимости
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Токен задайте в панели Render
