services:
  - type: worker
    name: betboom-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: python railway_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13  # Оставляем, но Render может использовать более новую версию
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Убедитесь, что токен задан в панели Render
