services:
  - type: worker
    name: betboom-bot
    env: docker
    plan: free
    image: python:3.13
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdrm2 libxkbcommon0 libgbm1 libnspr4 libnss3 libxcomposite1 libxdamage1 libxrandr2 xdg-utils libu2f-udev libvulkan1
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m playwright install chromium
      mkdir -p /opt/render/.cache/ms-playwright
      cp -r /root/.cache/ms-playwright/* /opt/render/.cache/ms-playwright/ || true
    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright
      python railway_bot.py
