services:
  - type: worker
    name: betboom-bot
    env: docker
    plan: free
    image: python:3.13

    buildCommand: |
      apt-get update && apt-get install -y wget curl unzip fonts-liberation libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

    startCommand: |
      bash -c '
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright
      if [ ! -d "$PLAYWRIGHT_BROWSERS_PATH/chromium-headless-shell" ]; then
        echo "⬇️ Устанавливаю Chromium (Playwright)..."
        playwright install --with-deps chromium
      fi
      echo "🚀 Запускаю бота..."
      python railway_bot.py
      '
