services:
  - type: worker
    name: betboom-bot
    env: docker
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      playwright install --with-deps chromium
      mkdir -p /opt/render/.cache/ms-playwright
      mv ~/.cache/ms-playwright/* /opt/render/.cache/ms-playwright/ || true
    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright
      python railway_bot.py
    image: python:3.13
