services:
  - type: worker
    name: betboom-24-7
    env: python
    runtime: python-3.11.9  # ✅ стабильная версия Python

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install greenlet==3.0.3
      pip install -r requirements.txt

    startCommand: |
      echo "🚀 Запуск BetBoom бота..."
      while true; do
        python railway_bot.py || echo "⚠️ Бот упал, перезапуск через 5 секунд..."
        sleep 5
      done

    autoDeploy: true  # 🔁 Render автоматически пересобирает и перезапускает после push
